In [1]:
import tensorflow as tf
import numpy as np
from common import *

import logging
import os, time
import tflearn
import tflearn.helpers.summarizer as s
from io import StringIO
import copy
import pickle
from functools import partial
import datetime

from sklearn.model_selection import train_test_split

logging.basicConfig(level=logging.DEBUG)

# Prepare word vectors

In [3]:
w2v_model = Word2Vec.load(join(DATA_FOLDER, 'vectors/w2v_model_300_w10'))

2017-08-23 10:20:03,354 : INFO : loading Word2Vec object from ../data/vectors/w2v_model_300_w10
2017-08-23 10:20:06,546 : INFO : loading wv recursively from ../data/vectors/w2v_model_300_w10.wv.* with mmap=None
2017-08-23 10:20:06,548 : INFO : loading syn0 from ../data/vectors/w2v_model_300_w10.wv.syn0.npy with mmap=None
2017-08-23 10:20:06,849 : INFO : setting ignored attribute syn0norm to None
2017-08-23 10:20:06,851 : INFO : loading syn1neg from ../data/vectors/w2v_model_300_w10.syn1neg.npy with mmap=None
2017-08-23 10:20:07,159 : INFO : setting ignored attribute cum_table to None
2017-08-23 10:20:07,160 : INFO : loaded ../data/vectors/w2v_model_300_w10


In [4]:
word_embeddings = w2v_model.wv.syn0.copy()
index2word = copy.deepcopy(w2v_model.wv.index2word)
del w2v_model

In [5]:
index2word.insert(0, 'PAD')
with open(join(DATA_FOLDER, "dictionary.pickle"), "wb") as output_file:
    pickle.dump(index2word, output_file)

In [6]:
stds = np.apply_along_axis(np.std, 1, word_embeddings)
pd.Series(stds).describe()

count    680760.000000
mean          0.193705
std           0.070574
min           0.000910
25%           0.137368
50%           0.178099
75%           0.244486
max           0.744395
dtype: float64

In [7]:
# 0.34 is chosen so the unknown vectors have (approximately) same variance as pre-trained ones
pad_vec = np.random.uniform(-0.34,0.34, word_embeddings.shape[1])
np.std(pad_vec)

0.18944918087888768

In [8]:
word_embeddings = np.insert(word_embeddings, 0, pad_vec, axis=0)

In [9]:
np.save(join(DATA_FOLDER, 'word_embeddings_%s.npy' % word_embeddings.shape[1]), word_embeddings)

# Load input data

In [2]:
word_embeddings = np.load(join(DATA_FOLDER, 'word_embeddings_300.npy'))
with open(join(DATA_FOLDER, "dictionary.pickle"), "rb") as input_file:
    index2word = pickle.load(input_file)

In [3]:
ids = glob('../data/corpus/**.txt')
with open(join(DATA_FOLDER, 'sims.json'), 'r') as f:
    sims = json.load(f)

In [4]:
# random select nagative examples
import random

def full_name(_id):
    return join(DATA_FOLDER, 'corpus/%s.txt' % _id)

def random_triples(sims, ids, num_epochs=1, seed=0):
    """
    Get random triples, select negatives at random in each epoch.
    Output: [anchor, positive, negative]
    """
    random.seed(0)
    ixs = list(range(len(ids)))
    for ep in range(num_epochs):
        random.shuffle(ixs)
        it = iter(ixs)
        for k, v in tqdm(sims.items()):
            exclude = [full_name(i) for i in [k] + v]
            for vi in v:
                ix = next(it)
                _neg = ids[ix]
                while _neg in exclude:
                    ix = next(it)
                    _neg = ids[ix]
                yield [full_name(k), full_name(vi), _neg]

# Input pipline

In [20]:
def parse_csv(text):
    with tf.name_scope('parse_csv'):
        strings = tf.string_split([text], delimiter='\n')
        raw_nums = tf.string_split(strings.values)
        nums = tf.string_to_number(raw_nums.values, tf.int32)
        dense = tf.sparse_to_dense(
            raw_nums.indices, raw_nums.dense_shape, nums, default_value=0)
        dense.set_shape(raw_nums.get_shape())
    return dense

def read_input_tuple(filename_queue):
    with tf.name_scope('read_input_tuple'):
        fnames = filename_queue.dequeue()
        example = []
        for fn in tf.unstack(fnames):
            record_string = tf.read_file(fn)
            arr = parse_csv(record_string)
            example.append(arr)
    return example

def input_pipeline(triples, batch_size, num_epochs=1, num_threads=cpu_count, shuffle=True):
    filename_queue = tf.train.input_producer(
        triples, num_epochs=num_epochs, capacity=32, shuffle=shuffle, seed=0)
    example = read_input_tuple(filename_queue)

    min_after_dequeue = 10000
    capacity = min_after_dequeue + 3 * batch_size
    anchor, positive, negative = tf.train.batch(
        example,
        batch_size=batch_size,
        capacity=capacity,
        dynamic_pad=True,
        #         allow_smaller_final_batch=True,
        num_threads=num_threads)
    return anchor, positive, negative

# Model definition

In [28]:
class TextCNN(object):
    def __init__(self,
                 n_sents,
                 n_words,
                 vocab_size,
                 embedding_size,
                 sent_filter_sizes=[2, 3, 4, 5],
                 sent_nb_filter=15,
                 doc_filter_sizes=[1, 2, 3],
                 doc_nb_filter=10,
                 sent_kmax=10,
                 doc_kmax=10,
                 learning_rate=0.001):
        self.n_sents = n_sents
        self.n_words = n_words
        self.vocab_size = vocab_size
        self.embedding_size = embedding_size
        self.sent_filter_sizes = sent_filter_sizes
        self.sent_nb_filter = sent_nb_filter
        self.doc_filter_sizes = doc_filter_sizes
        self.doc_nb_filter = doc_nb_filter
        self.sent_kmax = sent_kmax
        self.doc_kmax = doc_kmax
        self.learning_rate = learning_rate

        self.global_step = tf.get_variable("global_step", initializer=tf.constant(0), trainable=False)
        self.dropout_prob = tf.placeholder(tf.float32, name="dropout_prob")
        self.optimizer = tf.train.AdamOptimizer(
            learning_rate=learning_rate, beta1=0.9, beta2=0.999, epsilon=1e-08)

        # Embedding layer
        with tf.device('/cpu:0'), tf.name_scope("embedding"):
            self.LT = tf.get_variable('LT',
                initializer=tf.constant(0.0, shape=[vocab_size, embedding_size]),
                trainable=False)

            self.embedding_placeholder = tf.placeholder(
                tf.float32, [self.vocab_size, self.embedding_size])
            self.embedding_init = self.LT.assign(self.embedding_placeholder)

        with tf.variable_scope('sent'):
            self._create_sharable_weights(sent_filter_sizes, embedding_size,
                                          sent_nb_filter)
            self.sent_embedding_size = tf.convert_to_tensor(
                sent_kmax * sent_nb_filter * len(sent_filter_sizes))

        with tf.variable_scope('doc'):
            self._create_sharable_weights(doc_filter_sizes,
                                          self.sent_embedding_size.eval(),
                                          doc_nb_filter)
            self.doc_embedding_size = tf.convert_to_tensor(
                doc_kmax * doc_nb_filter * len(doc_filter_sizes))

    def inference(self, X):
        """ This is the forward calculation from batch X to doc embeddins """
        
        embedded_words = tf.nn.embedding_lookup(self.LT, X)
        embedded_words_expanded = tf.expand_dims(embedded_words, -1)
        
        with tf.variable_scope('sent'):

            def convolv_on_sents(embeds):
                return self._convolv_on_embeddings(
                    embeds, self.sent_filter_sizes, self.sent_nb_filter,
                    self.sent_kmax)

            # iter over each document
            self.sent_embed = tf.map_fn(
                convolv_on_sents,
                embedded_words_expanded,
                parallel_iterations=10,
                name='iter_over_docs')
            # sent_embed shape is [batch, n_sent, sent_sent_kmax*sent_nb_filter*len(sent_filter_sizes), 1]

        with tf.variable_scope('doc'):
            # finally, convolv on documents
            self.doc_embed = self._convolv_on_embeddings(
                self.sent_embed, self.doc_filter_sizes, self.doc_nb_filter,
                self.doc_kmax)
            # doc_embed shape is [batch, doc_kmax*doc_nb_filter*len(doc_filter_sizes), 1]

        doc_embed_normalized = tf.nn.l2_normalize(
            self.doc_embed, dim=1, name='doc_embed_normalized')

        return doc_embed_normalized

    def loss(self, X):
        with tf.name_scope("loss"):
            doc_embed_normalized = self.inference(X)
            self.anchor, self.positive, self.negative = tf.unstack(
                tf.reshape(doc_embed_normalized, [-1, 3, self.doc_embedding_size]),
                3, 1)
            _loss = triplet_loss(self.anchor, self.positive, self.negative)
        return _loss

    def optimize(self, X):
        with tf.name_scope("optimize"):
            self.loss_op = self.loss(X)
            self.gradients = self.optimizer.compute_gradients(self.loss_op)
            apply_gradient_op = self.optimizer.apply_gradients(
                self.gradients, global_step=self.global_step)
        return apply_gradient_op

    def _convolv_on_embeddings(self, embeds, filter_sizes, nb_filter, kmax):
        """
        Create a convolution + k-max pool layer for each filter size, then concat and vectorize.
        embeds shape is [batch, (n_words or n_sents), embedding_size, 1]
        """
        pooled_outputs = []
        for fsize in filter_sizes:
            with tf.name_scope("conv-%s" % fsize):
                with tf.variable_scope(
                        "conv_weights_fsize-%s" % fsize, reuse=True):
                    weights_init = tf.get_variable('W')
                    bias_init = tf.get_variable('b')
                conv = tf.nn.conv2d(
                    embeds,
                    weights_init,
                    strides=[1, 1, 1, 1],
                    padding="VALID",
                    name="conv")

                h = tf.nn.relu(tf.nn.bias_add(conv, bias_init), name="relu")
#                 h shape is [batch, n_words - fsize + 1, 1, nb_filter]
#             tf.summary.histogram("relu", h)

            with tf.name_scope('%s-maxpool-fsize-%s' % (kmax, fsize)):
                # k-maxpooling over the outputs
                trans = tf.transpose(h, perm=[0, 2, 3, 1])
                values, indices = tf.nn.top_k(trans, k=kmax, sorted=False)
                pooled = tf.transpose(values, perm=[0, 3, 1, 2])
                # pooled shape is [batch, kmax, 1, nb_filter]
                pooled_outputs.append(pooled)

        with tf.name_scope('concat_and_vectorize'):
            # Combine all the pooled features
            h_pool = tf.concat(pooled_outputs, 3)
            # h_pool shape is [batch, kmax, 1, nb_filter*len(filter_sizes)]

            # Vectorize filters for each sent to get sent embeddings
            trans = tf.transpose(h_pool, perm=[0, 2, 3, 1])
            batch = tf.shape(embeds)[0]
            sent_embed = tf.reshape(trans, [batch, -1, 1])
            # sent_embed shape is [batch, kmax*nb_filter*len(filter_sizes), 1]

        return sent_embed

    def _create_sharable_weights(self, filter_sizes, embedding_size,
                                 nb_filter):
        """ Create sharable weights for each type of convolution """
        with tf.name_scope('sharable_weights'):
            for fsize in filter_sizes:
                with tf.variable_scope("conv_weights_fsize-%s" % fsize):
                    filter_shape = [fsize, embedding_size, 1, nb_filter]
                    initializer = tf.contrib.layers.xavier_initializer_conv2d(
                        uniform=True)
#                     initializer=tf.truncated_normal(stddev=0.1))
                    weights_init = tf.get_variable(
                        'W', filter_shape, initializer=initializer)
                    bias_init = tf.get_variable(
                        'b', initializer=tf.constant(0.1, shape=[nb_filter]))
        
        
def triplet_loss(anchor_embed,
                 positive_embed,
                 negative_embed,
                 margin=0.2):
    """
    input: Three L2 normalized tensors of shape [None, dim], compute on a batch
    output: float
    """
    with tf.variable_scope('triplet_loss'):
        d_pos = tf.reduce_sum(tf.square(anchor_embed - positive_embed), 1)
        d_neg = tf.reduce_sum(tf.square(anchor_embed - negative_embed), 1)

        loss = tf.maximum(0., margin + d_pos - d_neg)
        loss = tf.reduce_mean(loss)

    return loss


In [7]:
triples_all = list(random_triples(sims, ids, num_epochs=1, seed=1))

100%|██████████| 368458/368458 [00:10<00:00, 33884.90it/s]


In [8]:
_triples, triples_test = train_test_split(triples_all, test_size=0.2, random_state=0)
triples_train, triples_val = train_test_split(_triples, test_size=0.3, random_state=0)

In [9]:
print(len(triples_train), len(triples_val), len(triples_test))

(428414, 183606, 153005)


In [ ]:
start_time = time.time()

vocab_size, embedding_size = word_embeddings.shape
n_sents, n_words = 123, 40

with tf.Graph().as_default():
    tf.set_random_seed(0)

    session_conf = tf.ConfigProto(
        allow_soft_placement=True, log_device_placement=False)
    sess = tf.Session(config=session_conf)
    with sess.as_default():
        anchor_batch, positive_batch, negative_batch = input_pipeline(
            triples_train[:64*100], batch_size=64, num_epochs=1)
        X = tf.reshape(
            tf.transpose([anchor_batch, positive_batch, negative_batch],
                         [1, 0, 2, 3]), [-1, n_sents, n_words],
            name='X')

        with tf.name_scope('init_model'):
            model = TextCNN(
                n_sents,
                n_words,
                vocab_size,
                embedding_size,
                sent_filter_sizes=[3, 4, 5],
                sent_nb_filter=50,
                doc_filter_sizes=[1, 2, 3],
                doc_nb_filter=10,
                sent_kmax=4,
                doc_kmax=10,
                learning_rate=0.001)
        train_op = model.optimize(X)

        init_local = tf.local_variables_initializer()
        init_global = tf.global_variables_initializer()
        sess.run([init_global, init_local])

        print('sent_embedding_size %s' % model.sent_embedding_size.eval())
        print('doc_embedding_size %s' % model.doc_embedding_size.eval())

        saver = tf.train.Saver()

        # ===================summary====================
        tf.summary.scalar("loss", model.loss_op)
        tf.summary.histogram("anchor", model.anchor)
        tf.summary.histogram("positive", model.positive)
        tf.summary.histogram("negative", model.negative)
        # Create summaries to visualize weights
        for var in tf.trainable_variables():
            tf.summary.histogram(var.name.replace(':', '_'), var)
        # Summarize all gradients
        for grad, var in model.gradients:
            tf.summary.histogram(
                var.name.replace(':', '_') + '/gradient', grad)
        merged_summary_op = tf.summary.merge_all()
        train_writer = tf.summary.FileWriter(
            join(DATA_FOLDER, 'summary', 'train',
                 str(datetime.datetime.now())), sess.graph)
        # ===================summary====================

        # Assign word embeddings to variable W
        #!!!! index is shifted by 1
        sess.run(
            model.embedding_init,
            feed_dict={model.embedding_placeholder: word_embeddings})

        # Start input enqueue threads.
        coord = tf.train.Coordinator()
        threads = tf.train.start_queue_runners(sess=sess, coord=coord)

        try:
            while not coord.should_stop():
                _, step, loss, summary, anchor = sess.run([
                    train_op, model.global_step, model.loss_op,
                    merged_summary_op, model.anchor
                ])
                current_step = tf.train.global_step(sess, model.global_step)
                train_writer.add_summary(summary, current_step)
                print(current_step, loss)
        except tf.errors.OutOfRangeError:
            print('Done training -- epoch limit reached')
        finally:
            # When done, ask the threads to stop.
            coord.request_stop()

        # Wait for threads to finish.
        coord.join(threads)

    saver.save(
        sess,
        join(DATA_FOLDER, 'models', '%s' % str(datetime.datetime.now())),
        global_step=current_step)

print("--- %s seconds ---" % (time.time() - start_time))

sent_embedding_size 600
doc_embedding_size 300
(1, 0.19604473)
(2, 0.19340082)
(3, 0.15896279)


In [53]:
model_dir = join(DATA_FOLDER, 'models')
!ls {model_dir}

2017-08-25 10:27:51.954244-1.data-00000-of-00001
2017-08-25 10:27:51.954244-1.index
2017-08-25 10:27:51.954244-1.meta
checkpoint


# Testing

https://github.com/aymericdamien/TensorFlow-Examples/blob/master/examples/4_Utils/save_restore_model.py

In [51]:
vocab_size, embedding_size = word_embeddings.shape
n_sents, n_words = 123, 40

doc_filter_sizes=[1, 2, 3]
doc_nb_filter=10
doc_kmax=10

with tf.Graph().as_default():
    tf.set_random_seed(0)

    session_conf = tf.ConfigProto(
        allow_soft_placement=True, log_device_placement=False)
    sess = tf.Session(config=session_conf)
    with sess.as_default():
        anchor_batch, positive_batch, negative_batch = input_pipeline(
            triples_test[:64*1], batch_size=64, num_epochs=1, num_threads=1, shuffle=False)
        X = tf.reshape(
            tf.transpose([anchor_batch, positive_batch, negative_batch],
                         [1, 0, 2, 3]), [-1, n_sents, n_words],
            name='X')
        
        init_local = tf.local_variables_initializer()
        init_global = tf.global_variables_initializer()
        sess.run([init_global, init_local])
        
        # do not restore before global initialization, otherwise all weights are set to default !!!
        saver = tf.train.import_meta_graph(
            join(model_dir, '2017-08-25 10:27:51.954244-1.meta'), input_map={'X':X})
        saver.restore(sess, tf.train.latest_checkpoint(model_dir))
        graph = tf.get_default_graph()
    
        doc_embed_normalized = graph.get_operation_by_name('optimize/loss/doc_embed_normalized').outputs[0]
        
        anchor, positive, negative = tf.unstack(
            tf.reshape(doc_embed_normalized, [-1, 3, doc_kmax * doc_nb_filter * len(doc_filter_sizes)]),
            3, 1)
        _loss = triplet_loss(anchor, positive, negative)
                             
        pprint([n.name for n in tf.get_default_graph().as_graph_def().node])
            
        # Start input enqueue threads.
        coord = tf.train.Coordinator()
        threads = tf.train.start_queue_runners(sess=sess, coord=coord)

        try:
            while not coord.should_stop():
                [doc_embeds, loss] = sess.run([doc_embed_normalized, _loss])
                print(doc_embeds.shape, loss)
        except tf.errors.OutOfRangeError:
            print('Done testing -- epoch limit reached')
        finally:
            # When done, ask the threads to stop.
            coord.request_stop()

        # Wait for threads to finish.
        coord.join(threads)

INFO:tensorflow:Restoring parameters from ../data/models/2017-08-25 10:27:51.954244-1


2017-08-25 10:42:10,266 : INFO : Restoring parameters from ../data/models/2017-08-25 10:27:51.954244-1


[u'input_producer/input_tensor',
 u'input_producer/limit_epochs/Const',
 u'input_producer/limit_epochs/epochs',
 u'input_producer/limit_epochs/epochs/Assign',
 u'input_producer/limit_epochs/epochs/read',
 u'input_producer/limit_epochs/CountUpTo',
 u'input_producer/limit_epochs',
 u'input_producer/FIFOQueueV2',
 u'input_producer/FIFOQueueV2_EnqueueMany',
 u'input_producer/FIFOQueueV2_Close',
 u'input_producer/FIFOQueueV2_Close_1',
 u'read_input_tuple/FIFOQueueV2_Dequeue',
 u'read_input_tuple/unstack',
 u'read_input_tuple/ReadFile',
 u'read_input_tuple/parse_csv/Const',
 u'read_input_tuple/parse_csv/packed',
 u'read_input_tuple/parse_csv/StringSplit',
 u'read_input_tuple/parse_csv/Const_1',
 u'read_input_tuple/parse_csv/StringSplit_1',
 u'read_input_tuple/parse_csv/StringToNumber',
 u'read_input_tuple/parse_csv/SparseToDense/default_value',
 u'read_input_tuple/parse_csv/SparseToDense',
 u'read_input_tuple/ReadFile_1',
 u'read_input_tuple/parse_csv_1/Const',
 u'read_input_tuple/parse_csv_

 u'sent/conv_weights_fsize-3/b/Adam/Initializer/zeros',
 u'sent/conv_weights_fsize-3/b/Adam',
 u'sent/conv_weights_fsize-3/b/Adam/Assign',
 u'sent/conv_weights_fsize-3/b/Adam/read',
 u'sent/conv_weights_fsize-3/b/Adam_1/Initializer/zeros',
 u'sent/conv_weights_fsize-3/b/Adam_1',
 u'sent/conv_weights_fsize-3/b/Adam_1/Assign',
 u'sent/conv_weights_fsize-3/b/Adam_1/read',
 u'sent/conv_weights_fsize-4/W/Adam/Initializer/zeros',
 u'sent/conv_weights_fsize-4/W/Adam',
 u'sent/conv_weights_fsize-4/W/Adam/Assign',
 u'sent/conv_weights_fsize-4/W/Adam/read',
 u'sent/conv_weights_fsize-4/W/Adam_1/Initializer/zeros',
 u'sent/conv_weights_fsize-4/W/Adam_1',
 u'sent/conv_weights_fsize-4/W/Adam_1/Assign',
 u'sent/conv_weights_fsize-4/W/Adam_1/read',
 u'sent/conv_weights_fsize-4/b/Adam/Initializer/zeros',
 u'sent/conv_weights_fsize-4/b/Adam',
 u'sent/conv_weights_fsize-4/b/Adam/Assign',
 u'sent/conv_weights_fsize-4/b/Adam/read',
 u'sent/conv_weights_fsize-4/b/Adam_1/Initializer/zeros',
 u'sent/conv_wei

In [52]:
doc_embeds[0]

array([[  2.15135096e-03],
       [  3.34364455e-03],
       [  4.21060761e-03],
       [  5.35907550e-03],
       [  3.74237960e-03],
       [  4.90200752e-03],
       [  8.94736219e-03],
       [  2.69345995e-02],
       [  7.67751178e-03],
       [  1.95799991e-02],
       [  2.56693140e-02],
       [  2.70236060e-02],
       [  2.64928043e-02],
       [  3.09367348e-02],
       [  3.12598534e-02],
       [  2.72800494e-02],
       [  6.07947446e-02],
       [  6.09909892e-02],
       [  3.44488584e-02],
       [  6.27180785e-02],
       [  3.20283435e-02],
       [  3.27057466e-02],
       [  3.69549282e-02],
       [  4.10346463e-02],
       [  3.43558230e-02],
       [  3.88845801e-02],
       [  3.93726751e-02],
       [  4.57564034e-02],
       [  5.06520569e-02],
       [  4.96000797e-02],
       [  2.49519907e-02],
       [  2.51020975e-02],
       [  2.75077075e-02],
       [  2.72912849e-02],
       [  2.66391281e-02],
       [  3.45628299e-02],
       [  2.85780299e-02],
 

In [72]:
1200000*1000/(93*60*60)

3584.2293906810037

In [213]:
g = tf.Graph()
with g.as_default():
    tf.set_random_seed(0)
    sess = tf.Session()
    with sess.as_default():

        a = tf.convert_to_tensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
        b = tf.convert_to_tensor([[[13,14],[15,16]],[[17,18],[19,20]],[[21,22],[23,24]]])
        c = tf.convert_to_tensor([[[25,26],[27,28]],[[29,30],[31,32]],[[33,34],[35,36]]])
        
        d = tf.reshape(tf.transpose([a,b,c], [1,0,2,3]), [-1,2,2])
        
        sess.run(tf.global_variables_initializer())
        
        [res] = sess.run([d])
        print(res)

#         train_writer = tf.summary.FileWriter('../data/summary', sess.graph)

[[[ 1  2]
  [ 3  4]]

 [[13 14]
  [15 16]]

 [[25 26]
  [27 28]]

 [[ 5  6]
  [ 7  8]]

 [[17 18]
  [19 20]]

 [[29 30]
  [31 32]]

 [[ 9 10]
  [11 12]]

 [[21 22]
  [23 24]]

 [[33 34]
  [35 36]]]
